# This is a basic workflow to help you get started with Actions
name: CI-Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  deploy_dev:
    name: "Deploy to Dev Instance"
    if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/feature/')
    strategy:
      fail-fast: true
      max-parallel: 1
    uses: ./.github/workflows/reusable-ci.yml
    with:
      target-env: 'DEV'
    secrets: inherit

  deploy_uat_and_prod:
    name: "Deploy to ${{ matrix.target }} Instance"
    if: github.ref == 'refs/heads/main'
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        target: [UAT, PROD]
    uses: ./.github/workflows/reusable-ci.yml
    with:
      target-env: ${{ matrix.target }}
    secrets: inherit