# This is a basic workflow to help you get started with Actions
name: CI-Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  deploy_dev:
    name: "Deploy to Dev Instance"
    if: ${{ github.ref }} == 'refs/head/develop'
    strategy:
      fail-fast: true
      max-parallel: 1
    uses: ./.github/workflows/reusable-ci.yml
    with:
      target-env: 'DEV'
    secrets: inherit

  deploy_dev_test:
      name: "Deploy to Dev Instance Test Should Not Run"
      if: false
      strategy:
        fail-fast: true
        max-parallel: 1
      uses: ./.github/workflows/reusable-ci.yml
      with:
        target-env: 'DEV'
      secrets: inherit